CREATE TABLE RPG_CLUB_RAW_MODAL_SESSIONS (
  SESSION_ID      VARCHAR2(120) PRIMARY KEY,
  OWNER_USER_ID   VARCHAR2(30) NOT NULL,
  FEATURE_ID      VARCHAR2(60) NOT NULL,
  FLOW_ID         VARCHAR2(60) NOT NULL,
  STATE_JSON      CLOB NOT NULL,
  STATUS          VARCHAR2(20) DEFAULT 'OPEN' NOT NULL,
  EXPIRES_AT      TIMESTAMP WITH TIME ZONE NOT NULL,
  GUILD_ID        VARCHAR2(30),
  CHANNEL_ID      VARCHAR2(30),
  CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

ALTER TABLE RPG_CLUB_RAW_MODAL_SESSIONS
  ADD CONSTRAINT CK_RAW_MODAL_SESSION_STATUS
  CHECK (STATUS IN ('OPEN', 'SUBMITTED', 'EXPIRED'));

CREATE INDEX IX_RAW_MODAL_SESS_OWNER_STATUS
  ON RPG_CLUB_RAW_MODAL_SESSIONS (OWNER_USER_ID, STATUS);

CREATE INDEX IX_RAW_MODAL_SESS_EXPIRES
  ON RPG_CLUB_RAW_MODAL_SESSIONS (EXPIRES_AT);

CREATE OR REPLACE TRIGGER TRG_RAW_MODAL_SESS_UPD
BEFORE UPDATE ON RPG_CLUB_RAW_MODAL_SESSIONS
FOR EACH ROW
BEGIN
  :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

COMMIT;
