-- Removes legacy per-row thread IDs from GOTM tables.
-- Thread associations are now sourced via THREAD_GAME_LINKS / THREADS using GAMEDB_GAME_ID.

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE GOTM_ENTRIES DROP COLUMN THREAD_ID';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -904 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE NR_GOTM_ENTRIES DROP COLUMN THREAD_ID';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -904 THEN
      RAISE;
    END IF;
END;
/
