CREATE TABLE RPG_CLUB_ADMIN_WIZARD_SESSIONS (
  SESSION_ID VARCHAR2(200) NOT NULL,
  COMMAND_KEY VARCHAR2(80) NOT NULL,
  OWNER_USER_ID VARCHAR2(64) NOT NULL,
  CHANNEL_ID VARCHAR2(64) NOT NULL,
  GUILD_ID VARCHAR2(64),
  STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  STATE_JSON CLOB NOT NULL,
  LAST_UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_RPG_CLUB_ADMIN_WIZARD_SESS PRIMARY KEY (SESSION_ID),
  CONSTRAINT CK_RPG_CLUB_ADMIN_WIZ_SESS_STATUS
    CHECK (STATUS IN ('ACTIVE', 'COMPLETED', 'CANCELLED'))
);

CREATE UNIQUE INDEX UX_RPG_CLUB_ADMIN_WIZ_ACTIVE
  ON RPG_CLUB_ADMIN_WIZARD_SESSIONS (COMMAND_KEY, OWNER_USER_ID, CHANNEL_ID, STATUS);

CREATE INDEX IX_RPG_CLUB_ADMIN_WIZ_OWNER_STATUS
  ON RPG_CLUB_ADMIN_WIZARD_SESSIONS (OWNER_USER_ID, STATUS, LAST_UPDATED_AT);

CREATE OR REPLACE TRIGGER TRG_RPG_CLUB_ADMIN_WIZ_SESS_UPD
BEFORE UPDATE ON RPG_CLUB_ADMIN_WIZARD_SESSIONS
FOR EACH ROW
BEGIN
  :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/
